version: 0.0
os: linux
files:
files:
  - source: src
    destination: /var/www/my-nodejs-app
  - source: scripts
    destination: /var/www/my-nodejs-app/scripts
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/clean_up.sh
      timeout: 300
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root